# 46_mi_dhcp_bind.sh - mi-dhcp-bind tab completion (auto-generated by tyro).
#
# Class A: lazy autoload — writes to the shell's standard completion dir,
# letting compinit (zsh) / bash-completion v2 (bash) load on first TAB.
#   zsh:  ~/.zfunc/_mi-dhcp-bind                    (in fpath via dot_zshrc.tmpl)
#   bash: ${XDG_DATA_HOME}/bash-completion/completions/mi-dhcp-bind
#
# Generator: `mi-dhcp-bind --tyro-write-completion {bash,zsh}` — runs the Python
# CLI as a subprocess (~500ms cold), so we mtime-check vs the binary and only
# regenerate when mi-dhcp-bind itself is newer than the cache. Force refresh:
# `mi-dhcp-bind-update-completion` (in dot_config/shell/10_aliases.sh).
#
# Sourced by both ~/.zshrc and ~/.bashrc via load_modular_dir.
# Sister pattern: 47_mi_router.sh (read-only inspector), 48_reyee.sh.

command -v mi-dhcp-bind >/dev/null 2>&1 || return 0

if [ -n "$ZSH_VERSION" ]; then
    _mdb_cache="${HOME}/.zfunc/_mi-dhcp-bind"
    _mdb_shell=zsh
elif [ -n "$BASH_VERSION" ]; then
    _mdb_cache="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/mi-dhcp-bind"
    _mdb_shell=bash
else
    return 0
fi

_mdb_bin="$(command -v mi-dhcp-bind)"
if [ ! -f "$_mdb_cache" ] || [ "$_mdb_bin" -nt "$_mdb_cache" ]; then
    mkdir -p "$(dirname "$_mdb_cache")"
    if [ "$_mdb_shell" = "zsh" ]; then
        # tyro emits `#compdef <fullpath>` — rewrite to the short name so
        # `mi-dhcp-bind<TAB>` (not `/full/path/mi-dhcp-bind<TAB>`) triggers compinit.
        _mdb_tmp="$(mktemp)"
        if mi-dhcp-bind --tyro-write-completion zsh "$_mdb_tmp" >/dev/null 2>&1; then
            { echo "#compdef mi-dhcp-bind"; tail -n +2 "$_mdb_tmp"; } > "$_mdb_cache"
        fi
        rm -f "$_mdb_tmp"
        unset _mdb_tmp
    else
        # tyro's bash output already binds basename via `complete -F`.
        mi-dhcp-bind --tyro-write-completion bash "$_mdb_cache" >/dev/null 2>&1
    fi
fi

unset _mdb_cache _mdb_shell _mdb_bin
