# 47_mi_router.sh - mi-router tab completion (auto-generated by tyro).
#
# Class A: lazy autoload — writes to the shell's standard completion dir,
# letting compinit (zsh) / bash-completion v2 (bash) load on first TAB.
#   zsh:  ~/.zfunc/_mi-router                       (in fpath via dot_zshrc.tmpl:68)
#   bash: ${XDG_DATA_HOME}/bash-completion/completions/mi-router
#
# Generator: `mi-router --tyro-write-completion {bash,zsh}` — runs the Python
# CLI as a subprocess (~500ms cold), so we mtime-check vs the binary and only
# regenerate when mi-router itself is newer than the cache. Force refresh:
# `mi-router-update-completion` (in dot_config/shell/10_aliases.sh).
#
# Sourced by both ~/.zshrc and ~/.bashrc via load_modular_dir.

command -v mi-router >/dev/null 2>&1 || return 0

if [ -n "$ZSH_VERSION" ]; then
    _mr_cache="${HOME}/.zfunc/_mi-router"
    _mr_shell=zsh
elif [ -n "$BASH_VERSION" ]; then
    _mr_cache="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/mi-router"
    _mr_shell=bash
else
    return 0
fi

_mr_bin="$(command -v mi-router)"
if [ ! -f "$_mr_cache" ] || [ "$_mr_bin" -nt "$_mr_cache" ]; then
    mkdir -p "$(dirname "$_mr_cache")"
    if [ "$_mr_shell" = "zsh" ]; then
        # tyro emits `#compdef <fullpath>` — rewrite to the short name so
        # `mi-router<TAB>` (not `/full/path/mi-router<TAB>`) triggers compinit.
        _mr_tmp="$(mktemp)"
        if mi-router --tyro-write-completion zsh "$_mr_tmp" >/dev/null 2>&1; then
            { echo "#compdef mi-router"; tail -n +2 "$_mr_tmp"; } > "$_mr_cache"
        fi
        rm -f "$_mr_tmp"
        unset _mr_tmp
    else
        # tyro's bash output already binds basename via `complete -F`.
        mi-router --tyro-write-completion bash "$_mr_cache" >/dev/null 2>&1
    fi
fi

unset _mr_cache _mr_shell _mr_bin
