# 48_reyee.sh - reyee tab completion (auto-generated by tyro).
#
# Class A: lazy autoload — writes to the shell's standard completion dir,
# letting compinit (zsh) / bash-completion v2 (bash) load on first TAB.
#   zsh:  ~/.zfunc/_reyee                            (in fpath via dot_zshrc.tmpl)
#   bash: ${XDG_DATA_HOME}/bash-completion/completions/reyee
#
# Generator: `reyee --tyro-write-completion {bash,zsh}` — runs the Python CLI
# as a subprocess (~500ms cold), so we mtime-check vs the binary and only
# regenerate when reyee itself is newer than the cache. Force refresh:
# `reyee-update-completion` (in dot_config/shell/10_aliases.sh).
#
# Sourced by both ~/.zshrc and ~/.bashrc via load_modular_dir.
# Mirrors dot_config/shell/47_mi_router.sh.

command -v reyee >/dev/null 2>&1 || return 0

if [ -n "$ZSH_VERSION" ]; then
    _ry_cache="${HOME}/.zfunc/_reyee"
    _ry_shell=zsh
elif [ -n "$BASH_VERSION" ]; then
    _ry_cache="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/reyee"
    _ry_shell=bash
else
    return 0
fi

_ry_bin="$(command -v reyee)"
if [ ! -f "$_ry_cache" ] || [ "$_ry_bin" -nt "$_ry_cache" ]; then
    mkdir -p "$(dirname "$_ry_cache")"
    if [ "$_ry_shell" = "zsh" ]; then
        # tyro emits `#compdef <fullpath>` — rewrite to the short name so
        # `reyee<TAB>` (not `/full/path/reyee<TAB>`) triggers compinit.
        _ry_tmp="$(mktemp)"
        if reyee --tyro-write-completion zsh "$_ry_tmp" >/dev/null 2>&1; then
            { echo "#compdef reyee"; tail -n +2 "$_ry_tmp"; } > "$_ry_cache"
        fi
        rm -f "$_ry_tmp"
        unset _ry_tmp
    else
        reyee --tyro-write-completion bash "$_ry_cache" >/dev/null 2>&1
    fi
fi

unset _ry_cache _ry_shell _ry_bin
