# 49_tsnet.sh - tsnet tab completion (auto-generated by tyro).
#
# Class A: lazy autoload — writes to the shell's standard completion dir,
# letting compinit (zsh) / bash-completion v2 (bash) load on first TAB.
#   zsh:  ~/.zfunc/_tsnet                            (in fpath via dot_zshrc.tmpl:68)
#   bash: ${XDG_DATA_HOME}/bash-completion/completions/tsnet
#
# Generator: `tsnet --tyro-write-completion {bash,zsh}` — runs the Python CLI as
# a subprocess (~500ms cold), so we mtime-check vs the binary and only
# regenerate when tsnet itself is newer than the cache. Force refresh:
# `tsnet-update-completion` (in dot_config/shell/10_aliases.sh).
#
# Machine names are deliberately NOT completed: enumerating the tailnet on every
# TAB round-trips the tailscaled socket. Use `tv tailnet` to pick a device.
#
# Sourced by both ~/.zshrc and ~/.bashrc via load_modular_dir.

command -v tsnet >/dev/null 2>&1 || return 0

if [ -n "$ZSH_VERSION" ]; then
    _ts_cache="${HOME}/.zfunc/_tsnet"
    _ts_shell=zsh
elif [ -n "$BASH_VERSION" ]; then
    _ts_cache="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/tsnet"
    _ts_shell=bash
else
    return 0
fi

_ts_bin="$(command -v tsnet)"
if [ ! -f "$_ts_cache" ] || [ "$_ts_bin" -nt "$_ts_cache" ]; then
    mkdir -p "$(dirname "$_ts_cache")"
    if [ "$_ts_shell" = "zsh" ]; then
        # tyro emits `#compdef <fullpath>` — rewrite to the short name so
        # `tsnet<TAB>` (not `/full/path/tsnet<TAB>`) triggers compinit.
        _ts_tmp="$(mktemp)"
        if tsnet --tyro-write-completion zsh "$_ts_tmp" >/dev/null 2>&1; then
            { echo "#compdef tsnet"; tail -n +2 "$_ts_tmp"; } > "$_ts_cache"
        fi
        rm -f "$_ts_tmp"
        unset _ts_tmp
    else
        # tyro's bash output already binds basename via `complete -F`.
        tsnet --tyro-write-completion bash "$_ts_cache" >/dev/null 2>&1
    fi
fi

unset _ts_cache _ts_shell _ts_bin
