# AI-powered review of past commands — pipes the Nth block to a coding-agent
# CLI in one-shot / advisory mode (agent prints its reply; no file edits).
# Depends on 03_tmux_capture.zsh for `cpblock`.
#
#   aifix [N] [-a AGENT] [-p PROMPT] [--raw] [--no-meta]
#   aiexplain [N] [-a AGENT] [-p PROMPT] [--raw] [--no-meta]
#   aiblock                                                    # Python TUI
#
# Agent auto-detection order: claude → opencode → codex → cursor-agent.
# Override via -a AGENT. Advisory-only by design; there is no --execute flag.
# For a back-and-forth interactive session, use `aiblock` → "Spawn agent".
#
# Env-var defaults (set in ~/.zshrc or a 99_local_*.zsh to override):
#
#   AICAP_CLAUDE_MODEL     default: haiku           (claude --model alias)
#   AICAP_OPENCODE_MODEL   default: github-copilot/claude-haiku-4.5
#   AICAP_CODEX_MODEL      default: gpt-5-mini
#   AICAP_CURSOR_MODEL     default: (unset — let cursor-agent pick)
#   AICAP_SHOW_METADATA    default: 1  (tokens / cost / model on stderr)
#                                        only extracted from claude JSON output
#                                        for now; other agents print agent
#                                        name + model only.
#   AICAP_PRETTIFY         default: 1  (auto: glow → bat → raw; non-tty = raw)
#
# Defaults are set below; do not edit this file to change them — `export
# AICAP_*=…` in your shell rc instead.

: "${AICAP_CLAUDE_MODEL:=haiku}"
: "${AICAP_OPENCODE_MODEL:=github-copilot/claude-haiku-4.5}"
: "${AICAP_CODEX_MODEL:=gpt-5-mini}"
: "${AICAP_CURSOR_MODEL:=}"
: "${AICAP_SHOW_METADATA:=1}"
: "${AICAP_PRETTIFY:=1}"

_aiagent_autodetect() {
  local cand
  for cand in claude opencode codex cursor-agent; do
    if command -v "$cand" &>/dev/null; then
      print -r -- "$cand"
      return 0
    fi
  done
  return 1
}

# Pretty-print stdin as Markdown: glow > bat > raw. Skips prettify if stdout
# is NOT a tty (so pipes stay clean) or AICAP_PRETTIFY=0.
_aicap_prettify() {
  if [[ "$AICAP_PRETTIFY" != "1" ]] || [[ ! -t 1 ]]; then
    cat
  elif command -v glow &>/dev/null; then
    glow -
  elif command -v bat &>/dev/null; then
    bat --language=md --style=plain --paging=never --color=always
  else
    cat
  fi
}

# Invoke a coding-agent in one-shot mode.
#
# Writes reply (text) to stdout. Writes metadata line to stderr when
# AICAP_SHOW_METADATA=1 and the agent supports structured JSON output.
# Currently only Claude's JSON includes usage/cost — other agents just get a
# "<agent> (<model>)" line on stderr.
_aiagent_invoke() {
  local agent=$1 prompt=$2
  local json reply model_used tokens_in tokens_out cost

  case "$agent" in
    claude)
      if [[ "$AICAP_SHOW_METADATA" == "1" ]] && command -v jq &>/dev/null; then
        json=$(claude -p --model "$AICAP_CLAUDE_MODEL" --output-format json "$prompt") || return $?
        reply=$(print -r -- "$json" | jq -r '.result // empty')
        # Model lives under `.modelUsage` as the object's only key (no top-level `.model`).
        model_used=$(print -r -- "$json" | jq -r '.modelUsage | keys | first // "?"')
        tokens_in=$(print -r -- "$json" | jq -r '.usage.input_tokens // "?"')
        tokens_out=$(print -r -- "$json" | jq -r '.usage.output_tokens // "?"')
        cache_read=$(print -r -- "$json" | jq -r '.usage.cache_read_input_tokens // 0')
        cache_create=$(print -r -- "$json" | jq -r '.usage.cache_creation_input_tokens // 0')
        cost=$(print -r -- "$json" | jq -r '.total_cost_usd // "?"')
        duration=$(print -r -- "$json" | jq -r '.duration_ms // "?"')
        print -u2 "claude ($model_used) | in=$tokens_in out=$tokens_out cache=(r:$cache_read,w:$cache_create) | cost=\$$cost ${duration}ms"
        print -r -- "$reply"
      else
        print -u2 "claude ($AICAP_CLAUDE_MODEL)"
        claude -p --model "$AICAP_CLAUDE_MODEL" "$prompt"
      fi
      ;;
    opencode)
      print -u2 "opencode ($AICAP_OPENCODE_MODEL)"
      opencode run -m "$AICAP_OPENCODE_MODEL" "$prompt"
      ;;
    codex)
      print -u2 "codex ($AICAP_CODEX_MODEL)"
      codex exec -m "$AICAP_CODEX_MODEL" "$prompt"
      ;;
    cursor-agent)
      if [[ -n "$AICAP_CURSOR_MODEL" ]]; then
        print -u2 "cursor-agent ($AICAP_CURSOR_MODEL)"
        cursor-agent -p --model "$AICAP_CURSOR_MODEL" "$prompt"
      else
        print -u2 "cursor-agent"
        cursor-agent -p "$prompt"
      fi
      ;;
    *) print -u2 "aifix: unknown agent '$agent' (supported: claude, opencode, codex, cursor-agent)"; return 1 ;;
  esac
}

# Shared dispatcher for aifix / aiexplain. Parses flags, captures the block,
# builds the prompt, invokes the agent, pipes reply through the prettifier.
_ai_capture_dispatch() {
  emulate -L zsh
  local name=$1; shift
  local default_prompt=$1; shift
  local n=1 agent="" prompt_override=""
  local raw=0 no_meta=0
  while (( $# )); do
    case "$1" in
      -a|--agent)   agent=$2; shift 2 ;;
      -p|--prompt)  prompt_override=$2; shift 2 ;;
      --raw)        raw=1; shift ;;
      --no-meta)    no_meta=1; shift ;;
      -h|--help)
        print -r -- "usage: $name [N] [-a AGENT] [-p PROMPT] [--raw] [--no-meta]"
        print -r -- "  N          block index back (default 1 = last)"
        print -r -- "  -a AGENT   claude | opencode | codex | cursor-agent (default: auto-detect)"
        print -r -- "  -p PROMPT  override default prompt"
        print -r -- "  --raw      disable prettify (glow/bat), print raw agent reply"
        print -r -- "  --no-meta  suppress the stderr metadata line"
        print -r -- ""
        print -r -- "env vars:"
        print -r -- "  AICAP_CLAUDE_MODEL   = ${AICAP_CLAUDE_MODEL}"
        print -r -- "  AICAP_OPENCODE_MODEL = ${AICAP_OPENCODE_MODEL}"
        print -r -- "  AICAP_CODEX_MODEL    = ${AICAP_CODEX_MODEL}"
        print -r -- "  AICAP_CURSOR_MODEL   = ${AICAP_CURSOR_MODEL:-<unset>}"
        print -r -- "  AICAP_SHOW_METADATA  = ${AICAP_SHOW_METADATA}"
        print -r -- "  AICAP_PRETTIFY       = ${AICAP_PRETTIFY}"
        return 0 ;;
      --) shift; break ;;
      -*) print -u2 "$name: unknown flag: $1"; return 1 ;;
      *)  n=$1; shift ;;
    esac
  done
  if [[ ! "$n" =~ ^[0-9]+$ ]] || (( n < 1 )); then
    print -u2 "$name: N must be a positive integer (got: $n)"
    return 1
  fi
  if [[ -z "$agent" ]]; then
    agent=$(_aiagent_autodetect) || {
      print -u2 "$name: no coding-agent CLI found on PATH (tried: claude, opencode, codex, cursor-agent)"
      return 1
    }
  fi
  local block
  block=$(cpblock "$n" 2>/dev/null) || {
    print -u2 "$name: cpblock $n failed (run 'exec zsh' if the shell pre-dates chezmoi apply)"
    return 1
  }
  if [[ -z "$block" ]]; then
    print -u2 "$name: cpblock $n returned empty"
    return 1
  fi
  local prompt="${prompt_override:-$default_prompt}

$block"
  print -u2 "$name ← block -$n"

  # Per-call overrides: --no-meta and --raw flip env-var behaviour locally.
  local saved_show=$AICAP_SHOW_METADATA saved_pretty=$AICAP_PRETTIFY
  (( no_meta )) && AICAP_SHOW_METADATA=0
  (( raw ))    && AICAP_PRETTIFY=0

  if (( raw )); then
    _aiagent_invoke "$agent" "$prompt"
  else
    _aiagent_invoke "$agent" "$prompt" | _aicap_prettify
  fi
  local rc=$?

  AICAP_SHOW_METADATA=$saved_show
  AICAP_PRETTIFY=$saved_pretty
  return $rc
}

aifix() {
  _ai_capture_dispatch aifix \
    "Here is a command I ran in my terminal and its output. Diagnose any errors and suggest a concrete fix. Be brief and specific." \
    "$@"
}

aiexplain() {
  _ai_capture_dispatch aiexplain \
    "Here is a command I ran in my terminal and its output. Explain what happened in plain language. Be concise." \
    "$@"
}

# aiblock — launch the Python TUI (scripts/aiblock.py) resolved via
# chezmoi source-path, cached per-shell. The Python side reads the same
# AICAP_* env vars so model defaults stay consistent.
_AIBLOCK_SCRIPT=""
aiblock() {
  emulate -L zsh
  if [[ -z "$_AIBLOCK_SCRIPT" ]]; then
    local base
    base=$(chezmoi source-path 2>/dev/null) || {
      print -u2 "aiblock: could not resolve chezmoi source-path"
      return 1
    }
    _AIBLOCK_SCRIPT="$base/scripts/aiblock.py"
  fi
  if [[ ! -f "$_AIBLOCK_SCRIPT" ]]; then
    print -u2 "aiblock: $_AIBLOCK_SCRIPT not found (run 'chezmoi apply' after a git pull)"
    return 1
  fi
  uv run --script "$_AIBLOCK_SCRIPT" "$@"
}
