# AI-powered review of past commands — pipes the Nth block to a coding-agent
# CLI in one-shot / advisory mode (agent prints its reply; no file edits).
# Depends on 03_tmux_capture.zsh for `cpblock`.
#
#   aifix [N] [-a AGENT] [-p PROMPT] [--raw] [--no-meta]
#   aiexplain [N] [-a AGENT] [-p PROMPT] [--raw] [--no-meta]
#   aiblock                                                    # Python TUI
#
# Agent auto-detection order: claude → opencode → codex → cursor-agent.
# Override via -a AGENT. Advisory-only by design; there is no --execute flag.
# For a back-and-forth interactive session, use `aiblock` → "Spawn agent".
#
# Env-var defaults (set in ~/.zshrc or a 99_local_*.zsh to override):
#
#   AICAP_CLAUDE_MODEL     default: haiku           (claude --model alias)
#   AICAP_OPENCODE_MODEL   default: github-copilot/claude-haiku-4.5
#   AICAP_CODEX_MODEL      default: gpt-5-mini
#   AICAP_CURSOR_MODEL     default: (unset — let cursor-agent pick)
#   AICAP_SHOW_METADATA    default: 1  (tokens / cost / model on stderr)
#                                        only extracted from claude JSON output
#                                        for now; other agents print agent
#                                        name + model only.
#   AICAP_PRETTIFY         default: 1  (auto: glow → bat → raw; non-tty = raw)
#
# Defaults are set below; do not edit this file to change them — `export
# AICAP_*=…` in your shell rc instead.

: "${AICAP_CLAUDE_MODEL:=haiku}"
: "${AICAP_OPENCODE_MODEL:=github-copilot/claude-haiku-4.5}"
: "${AICAP_CODEX_MODEL:=gpt-5-mini}"
: "${AICAP_CURSOR_MODEL:=}"
: "${AICAP_SHOW_METADATA:=1}"
: "${AICAP_PRETTIFY:=1}"
: "${AICAP_SPINNER:=1}"

_aiagent_autodetect() {
  local cand
  for cand in claude opencode codex cursor-agent; do
    if command -v "$cand" &>/dev/null; then
      print -r -- "$cand"
      return 0
    fi
  done
  return 1
}

# Background spinner on stderr while the agent is thinking. Skipped when
# AICAP_SPINNER=0 or stderr isn't a tty (so pipes / file redirects stay
# clean). The spinner subprocess is disowned via `&!` so it survives the
# command substitution that invokes the agent.
_AICAP_SPIN_PID=
_aicap_spinner_start() {
  [[ "$AICAP_SPINNER" != "1" ]] && return 0
  [[ ! -t 2 ]] && return 0
  local label=${1:-thinking}
  (
    trap 'exit 0' TERM INT HUP
    local frames=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
    local i=0
    while true; do
      printf '\r\e[K%s %s' "${frames[$(( (i % 10) + 1 ))]}" "$label" >&2
      (( i++ ))
      sleep 0.1
    done
  ) &!
  _AICAP_SPIN_PID=$!
}

_aicap_spinner_stop() {
  [[ -z "$_AICAP_SPIN_PID" ]] && return 0
  kill "$_AICAP_SPIN_PID" 2>/dev/null
  # Drain; zsh waits on PIDs even if disowned as long as we know the PID.
  wait "$_AICAP_SPIN_PID" 2>/dev/null
  _AICAP_SPIN_PID=
  [[ -t 2 ]] && printf '\r\e[K' >&2
}

# Pretty-print stdin as Markdown: glow > bat > raw. Skips prettify if stdout
# is NOT a tty (so pipes stay clean) or AICAP_PRETTIFY=0.
_aicap_prettify() {
  if [[ "$AICAP_PRETTIFY" != "1" ]] || [[ ! -t 1 ]]; then
    cat
  elif command -v glow &>/dev/null; then
    glow -
  elif command -v bat &>/dev/null; then
    bat --language=md --style=plain --paging=never --color=always
  else
    cat
  fi
}

# Invoke a coding-agent in one-shot mode.
#
# Writes reply (text) to stdout. Writes metadata line to stderr when
# AICAP_SHOW_METADATA=1 and the agent supports structured JSON output.
# Currently only Claude's JSON includes usage/cost — other agents just get a
# "<agent> (<model>)" line on stderr.
_aiagent_invoke() {
  local agent=$1 prompt=$2
  local json reply model_used tokens_in tokens_out cache_read cache_create cost duration rc

  # Ensure spinner cleans up if the caller returns or we hit a trap.
  trap '_aicap_spinner_stop' EXIT INT TERM

  case "$agent" in
    claude)
      if [[ "$AICAP_SHOW_METADATA" == "1" ]] && command -v jq &>/dev/null; then
        _aicap_spinner_start "claude $AICAP_CLAUDE_MODEL (json)…"
        json=$(claude -p --model "$AICAP_CLAUDE_MODEL" --output-format json "$prompt")
        rc=$?
        _aicap_spinner_stop
        (( rc != 0 )) && return $rc
        reply=$(print -r -- "$json" | jq -r '.result // empty')
        model_used=$(print -r -- "$json" | jq -r '.modelUsage | keys | first // "?"')
        tokens_in=$(print -r -- "$json" | jq -r '.usage.input_tokens // "?"')
        tokens_out=$(print -r -- "$json" | jq -r '.usage.output_tokens // "?"')
        cache_read=$(print -r -- "$json" | jq -r '.usage.cache_read_input_tokens // 0')
        cache_create=$(print -r -- "$json" | jq -r '.usage.cache_creation_input_tokens // 0')
        cost=$(print -r -- "$json" | jq -r '.total_cost_usd // "?"')
        duration=$(print -r -- "$json" | jq -r '.duration_ms // "?"')
        print -u2 "claude ($model_used) | in=$tokens_in out=$tokens_out cache=(r:$cache_read,w:$cache_create) | cost=\$$cost ${duration}ms"
        print -r -- "$reply"
      else
        print -u2 "claude ($AICAP_CLAUDE_MODEL)"
        _aicap_spinner_start "claude $AICAP_CLAUDE_MODEL…"
        claude -p --model "$AICAP_CLAUDE_MODEL" "$prompt"
        rc=$?
        _aicap_spinner_stop
        return $rc
      fi
      ;;
    opencode)
      print -u2 "opencode ($AICAP_OPENCODE_MODEL)"
      _aicap_spinner_start "opencode $AICAP_OPENCODE_MODEL…"
      opencode run -m "$AICAP_OPENCODE_MODEL" "$prompt"
      rc=$?
      _aicap_spinner_stop
      return $rc
      ;;
    codex)
      print -u2 "codex ($AICAP_CODEX_MODEL)"
      _aicap_spinner_start "codex $AICAP_CODEX_MODEL…"
      codex exec -m "$AICAP_CODEX_MODEL" "$prompt"
      rc=$?
      _aicap_spinner_stop
      return $rc
      ;;
    cursor-agent)
      if [[ -n "$AICAP_CURSOR_MODEL" ]]; then
        print -u2 "cursor-agent ($AICAP_CURSOR_MODEL)"
        _aicap_spinner_start "cursor-agent $AICAP_CURSOR_MODEL…"
        cursor-agent -p --model "$AICAP_CURSOR_MODEL" "$prompt"
      else
        print -u2 "cursor-agent"
        _aicap_spinner_start "cursor-agent…"
        cursor-agent -p "$prompt"
      fi
      rc=$?
      _aicap_spinner_stop
      return $rc
      ;;
    *) print -u2 "aifix: unknown agent '$agent' (supported: claude, opencode, codex, cursor-agent)"; return 1 ;;
  esac
}

# Core dispatcher: given an already-captured block, build the prompt, invoke
# the agent, pipe reply through the prettifier. Shared by the four sources:
# cpblock (aifix/aiexplain), stdin (aifix-stdin), tee'd CMD run (aifix-run),
# and thefuck-style rerun (aifix-rerun).
#
#   _ai_dispatch_core <name> <source-label> <default-prompt>
#                     <agent> <raw> <no-meta> <prompt-override> <block>
_ai_dispatch_core() {
  local name=$1 source_label=$2 default_prompt=$3
  local agent=$4 raw=$5 no_meta=$6 prompt_override=$7 block=$8
  if [[ -z "$block" ]]; then
    print -u2 "$name: empty block"
    return 1
  fi
  local prompt="${prompt_override:-$default_prompt}

$block"
  print -u2 "$name ← $source_label"

  # Per-call env overrides: --no-meta / --raw flip env-var behaviour locally
  # so _aiagent_invoke + _aicap_prettify see the intended values.
  local saved_show=$AICAP_SHOW_METADATA saved_pretty=$AICAP_PRETTIFY
  (( no_meta )) && AICAP_SHOW_METADATA=0
  (( raw ))    && AICAP_PRETTIFY=0

  if (( raw )); then
    _aiagent_invoke "$agent" "$prompt"
  else
    _aiagent_invoke "$agent" "$prompt" | _aicap_prettify
  fi
  local rc=$?

  AICAP_SHOW_METADATA=$saved_show
  AICAP_PRETTIFY=$saved_pretty
  return $rc
}

# Print the shared flag-help + env-var snapshot. Used by -h on each wrapper.
_ai_print_help() {
  local name=$1 usage=$2
  print -r -- "usage: $name $usage"
  print -r -- "  -a AGENT   claude | opencode | codex | cursor-agent (default: auto-detect)"
  print -r -- "  -p PROMPT  override default prompt"
  print -r -- "  --raw      disable prettify (glow/bat), print raw agent reply"
  print -r -- "  --no-meta  suppress the stderr metadata line"
  print -r -- ""
  print -r -- "env vars:"
  print -r -- "  AICAP_CLAUDE_MODEL   = ${AICAP_CLAUDE_MODEL}"
  print -r -- "  AICAP_OPENCODE_MODEL = ${AICAP_OPENCODE_MODEL}"
  print -r -- "  AICAP_CODEX_MODEL    = ${AICAP_CODEX_MODEL}"
  print -r -- "  AICAP_CURSOR_MODEL   = ${AICAP_CURSOR_MODEL:-<unset>}"
  print -r -- "  AICAP_SHOW_METADATA  = ${AICAP_SHOW_METADATA}"
  print -r -- "  AICAP_PRETTIFY       = ${AICAP_PRETTIFY}"
  print -r -- "  AICAP_SPINNER        = ${AICAP_SPINNER}"
}

# Shared dispatcher for aifix / aiexplain. Captures via cpblock.
_ai_capture_dispatch() {
  emulate -L zsh
  local name=$1; shift
  local default_prompt=$1; shift
  local n=1 agent="" prompt_override="" raw=0 no_meta=0
  while (( $# )); do
    case "$1" in
      -a|--agent)   agent=$2; shift 2 ;;
      -p|--prompt)  prompt_override=$2; shift 2 ;;
      --raw)        raw=1; shift ;;
      --no-meta)    no_meta=1; shift ;;
      -h|--help)    _ai_print_help "$name" "[N] [-a AGENT] [-p PROMPT] [--raw] [--no-meta]"
                    print -r -- "  N          block index back (default 1 = last)"
                    return 0 ;;
      --) shift; break ;;
      -*) print -u2 "$name: unknown flag: $1"; return 1 ;;
      *)  n=$1; shift ;;
    esac
  done
  if [[ ! "$n" =~ ^[0-9]+$ ]] || (( n < 1 )); then
    print -u2 "$name: N must be a positive integer (got: $n)"
    return 1
  fi
  if [[ -z "$agent" ]]; then
    agent=$(_aiagent_autodetect) || {
      print -u2 "$name: no coding-agent CLI found on PATH (tried: claude, opencode, codex, cursor-agent)"
      return 1
    }
  fi
  local block
  block=$(cpblock "$n" 2>/dev/null) || {
    print -u2 "$name: cpblock $n failed (run 'exec zsh' if the shell pre-dates chezmoi apply)"
    return 1
  }
  _ai_dispatch_core "$name" "block -$n" "$default_prompt" \
    "$agent" "$raw" "$no_meta" "$prompt_override" "$block"
}

aifix() {
  _ai_capture_dispatch aifix \
    "Here is a command I ran in my terminal and its output. Diagnose any errors and suggest a concrete fix. Be brief and specific." \
    "$@"
}

aiexplain() {
  _ai_capture_dispatch aiexplain \
    "Here is a command I ran in my terminal and its output. Explain what happened in plain language. Be concise." \
    "$@"
}

# -----------------------------------------------------------------------------
# Non-tmux Tier 1: stdin / run / rerun sources
# -----------------------------------------------------------------------------
# These three cover the "no tmux available" case (VSCode integrated terminal,
# bare Ghostty without tmux, quick SSH) by NOT relying on cpblock / OSC 133.
# Each composes zero magic — user explicitly picks the source.
#
# See backlog/ai-capture-non-tmux-output.md for why we don't do automatic
# tee redirection (Tier 2) or PTY proxy wrapping (Tier 3).

# aifix-stdin: read whatever the caller piped in. Universal.
#   tail -200 /var/log/nginx/error.log | aifix-stdin
#   curl -sS https://weird.api/thing | aifix-stdin -p "explain this JSON"
#   aifix-stdin < build.log
aifix-stdin() {
  emulate -L zsh
  local name=aifix-stdin agent="" prompt_override="" raw=0 no_meta=0
  local default_prompt="Here is output captured from my terminal. Diagnose any errors and suggest a concrete fix. Be brief and specific."
  while (( $# )); do
    case "$1" in
      -a|--agent)   agent=$2; shift 2 ;;
      -p|--prompt)  prompt_override=$2; shift 2 ;;
      --raw)        raw=1; shift ;;
      --no-meta)    no_meta=1; shift ;;
      -h|--help)    _ai_print_help "$name" "[-a AGENT] [-p PROMPT] [--raw] [--no-meta]"
                    print -r -- "  Reads block from stdin. No tmux / cpblock dependency."
                    return 0 ;;
      *) print -u2 "$name: unexpected arg: $1 (did you mean -p?)"; return 1 ;;
    esac
  done
  if [[ -z "$agent" ]]; then
    agent=$(_aiagent_autodetect) || {
      print -u2 "$name: no coding-agent CLI found on PATH"
      return 1
    }
  fi
  # -t 0 checks if stdin is a terminal. If it is, user likely forgot to pipe.
  if [[ -t 0 ]]; then
    print -u2 "$name: stdin is a tty — did you forget to pipe? Example:"
    print -u2 "  some-command 2>&1 | $name"
    return 1
  fi
  local block
  block=$(cat)
  _ai_dispatch_core "$name" "stdin" "$default_prompt" \
    "$agent" "$raw" "$no_meta" "$prompt_override" "$block"
}

# aifix-run: run CMD, tee stdout+stderr to a log, feed "$ CMD\n<output>\n(exit code: N)"
# to the agent. Use `--` to separate flags from the command.
#   aifix-run -- cargo build --release
#   aifix-run -p "is this safe?" -- ansible-playbook deploy.yml
#
# isatty caveat: teeing makes CMD's stdout a pipe, so TUI apps (vim, less)
# render in degraded mode. Don't use this for interactive tools.
aifix-run() {
  emulate -L zsh
  local name=aifix-run agent="" prompt_override="" raw=0 no_meta=0
  local default_prompt="Here is a command I ran in my terminal and its output. Diagnose any errors and suggest a concrete fix. Be brief and specific."
  while (( $# )); do
    case "$1" in
      -a|--agent)   agent=$2; shift 2 ;;
      -p|--prompt)  prompt_override=$2; shift 2 ;;
      --raw)        raw=1; shift ;;
      --no-meta)    no_meta=1; shift ;;
      -h|--help)    _ai_print_help "$name" "[-a AGENT] [-p PROMPT] [--raw] [--no-meta] -- CMD [ARG...]"
                    print -r -- "  Runs CMD with stdout+stderr teed to a log, feeds to agent."
                    print -r -- "  Use \`--\` to separate flags from the command."
                    return 0 ;;
      --) shift; break ;;
      -*) print -u2 "$name: unknown flag: $1"; return 1 ;;
      *) break ;;
    esac
  done
  if (( $# == 0 )); then
    print -u2 "$name: missing command. Usage: $name [flags] -- CMD [ARG...]"
    return 1
  fi
  if [[ -z "$agent" ]]; then
    agent=$(_aiagent_autodetect) || {
      print -u2 "$name: no coding-agent CLI found on PATH"
      return 1
    }
  fi
  local log
  log=$(mktemp -t aifix-run.XXXXXX) || { print -u2 "$name: mktemp failed"; return 1; }
  # Record the command line as the block's first line so the agent knows
  # what was run. Use $(print -r -- "$*") to preserve args verbatim.
  print -r -- "\$ $*" > "$log"
  "$@" 2>&1 | tee -a "$log"
  local rc=${pipestatus[1]}
  print -r -- "" >> "$log"
  print -r -- "(exit code: $rc)" >> "$log"
  local block
  block=$(<"$log")
  rm -f "$log"
  _ai_dispatch_core "$name" "run \`${1}…\` (exit $rc)" "$default_prompt" \
    "$agent" "$raw" "$no_meta" "$prompt_override" "$block"
}

# aifix-rerun: thefuck-style. Re-executes the last command from shell history
# via aifix-run. Prompts for confirmation unless -y, because re-running has
# side effects if the command isn't idempotent.
aifix-rerun() {
  emulate -L zsh
  local name=aifix-rerun yes=0 forward=()
  while (( $# )); do
    case "$1" in
      -y|--yes) yes=1; shift ;;
      -h|--help) _ai_print_help "$name" "[-y] [-a AGENT] [-p PROMPT] [--raw] [--no-meta]"
                 print -r -- "  Re-executes the last command from zsh history via aifix-run."
                 print -r -- "  Prompts for confirmation unless -y (side effects beware)."
                 return 0 ;;
      *) forward+=("$1"); shift ;;
    esac
  done
  # fc -ln -2 -2: skip aifix-rerun itself (which is -1), grab the one before.
  local cmd
  cmd=$(fc -ln -2 -2 2>/dev/null)
  cmd="${cmd#	}"; cmd="${cmd# }"
  if [[ -z "$cmd" ]]; then
    print -u2 "$name: no prior command in shell history"
    return 1
  fi
  print -u2 "$name: will re-execute:"
  print -u2 "  $cmd"
  print -u2 "⚠ side effects if the command is not idempotent (network calls, file writes, etc.)"
  if (( ! yes )); then
    local reply
    read -q "reply?Proceed? [y/N] "
    print
    [[ "$reply" != "y" ]] && { print -u2 "$name: aborted"; return 130; }
  fi
  # Delegate to aifix-run via eval (preserves quoting for $cmd's shell syntax).
  eval "aifix-run ${forward[*]} -- $cmd"
}

# aiblock — launch the Python TUI (scripts/aiblock.py) resolved via
# chezmoi source-path, cached per-shell. The Python side reads the same
# AICAP_* env vars so model defaults stay consistent.
#
# History passing: `fc -ln …` only works inside this interactive zsh —
# a `zsh -ic` subshell doesn't inherit the in-memory history buffer and
# `fc -R` only pulls whatever the HISTFILE has on disk (which misses
# unflushed recent commands). Dump the current shell's history into a
# temp file and hand the path to the TUI via $AIBLOCK_HIST_DUMP.
_AIBLOCK_SCRIPT=""
aiblock() {
  emulate -L zsh
  if [[ -z "$_AIBLOCK_SCRIPT" ]]; then
    local base
    base=$(chezmoi source-path 2>/dev/null) || {
      print -u2 "aiblock: could not resolve chezmoi source-path"
      return 1
    }
    _AIBLOCK_SCRIPT="$base/scripts/aiblock.py"
  fi
  if [[ ! -f "$_AIBLOCK_SCRIPT" ]]; then
    print -u2 "aiblock: $_AIBLOCK_SCRIPT not found (run 'chezmoi apply' after a git pull)"
    return 1
  fi
  local histdump
  histdump=$(mktemp -t aiblock-hist.XXXXXX) || {
    print -u2 "aiblock: mktemp failed"
    return 1
  }
  # fc -ln -30: last 30 entries, no numbering. Trailing newline per entry.
  fc -ln -30 > "$histdump" 2>/dev/null
  AIBLOCK_HIST_DUMP="$histdump" uv run --script "$_AIBLOCK_SCRIPT" "$@"
  local rc=$?
  rm -f "$histdump"
  return $rc
}
