# aisuggest — prompt-time NL→shell ghost text via the existing _aiagent_invoke
# layer. Press the trigger (Alt+; default) to translate the current BUFFER from
# natural language into a single shell command, shown as ghost text. Tab or →
# accepts; any other keypress dismisses.
#
# Integrates with 04_ai_capture.zsh (_aiagent_invoke / _aiagent_autodetect) so
# the same agent autodetect (claude → opencode → codex → cursor-agent) and the
# same AICAP_*_MODEL defaults apply. No API key needed when claude / opencode /
# codex / cursor-agent CLIs are authenticated.
#
# Env-var defaults (set in ~/.zshrc.adhoc or ~/.config/zsh/secrets.zsh to
# override; do not edit this file):
#
#   AISUGGEST_KEY              default: ^[;            (Alt+;)
#   AISUGGEST_AGENT            default: empty          (autodetect at invoke)
#   AISUGGEST_MODEL            default: empty          (use AICAP_*_MODEL)
#   AISUGGEST_HIGHLIGHT        default: fg=8           (region_highlight style)
#   AISUGGEST_PROMPT_OVERRIDE  default: empty          (replace built-in prompt)
#   AISUGGEST_DEBUG            default: 0              (1 = log every widget step
#                                                       to $AISUGGEST_LOG;
#                                                       runtime-toggleable)
#   AISUGGEST_LOG              default: /tmp/aisuggest.log
#
# Debugging:
#   `aisuggest "<text>"`              CLI form — same pipeline as the widget,
#                                     prints the suggestion to stdout.
#   `aisuggest --debug "<text>"`      Also prints raw / sanitized / final to
#                                     stderr layer-by-layer.
#   `export AISUGGEST_DEBUG=1`        Trace every widget step to $AISUGGEST_LOG.
#
# Architecture + design notes: docs/tools/zsh-inline-ai.md
#
# Roadmap (full rationale + upstream pointers in the doc above, "Roadmap" section):
#   1. Low-latency claude flag profile — bypass _aiagent_invoke for `agent==claude`,
#      shell out with `--no-session-persistence --effort low --no-chrome --tools ""
#      --setting-sources "" --system-prompt "$sys" "$user_input"`. ~1.5x faster.
#      Upstream ref: providers/claude-code.zsh.
#   2. Pass system prompt via `--system-prompt` flag instead of concatenating into
#      the user message. Tighter rule-following.
#   3. Async via `zle -F <fd>`. Currently we block the prompt during the agent call.
#      A non-blocking flow (background agent → FD watcher → render-on-arrival) lets
#      the user keep typing while the suggestion renders.
#   4. Direct API providers (anthropic / openai / gemini via curl + jq) for users
#      without any of the four CLIs installed. Pair with a key-retrieval-command
#      env var (1Password / pass / GNOME Keyring / AWS Secrets Manager).
#   5. Sanitize regression test (port upstream's test-sanitize.sh — crafted ANSI /
#      control-char payloads → assert _aisuggest_sanitize strips them).
#   6. Per-agent model env vars (AISUGGEST_CLAUDE_MODEL, AISUGGEST_OPENCODE_MODEL, …)
#      so users can pin different models per agent without re-exporting on switch.

# Prevent double-load (creates nested widget wrappers)
(( ${+functions[_aisuggest_widget]} )) && return

# Hard preconditions — bail silently if anything is missing.
[[ -o zle ]] || return 0
command -v curl &>/dev/null || return 0
command -v jq   &>/dev/null || return 0
(( ${+functions[_aiagent_invoke]} )) || return 0
(( ${+functions[_aiagent_autodetect]} )) || return 0
_aiagent_autodetect &>/dev/null || return 0

# ============================================================================
# Configuration
# ============================================================================
typeset -g AISUGGEST_KEY=${AISUGGEST_KEY:-'^[;'}
typeset -g AISUGGEST_AGENT=${AISUGGEST_AGENT:-''}
typeset -g AISUGGEST_MODEL=${AISUGGEST_MODEL:-''}
typeset -g AISUGGEST_HIGHLIGHT=${AISUGGEST_HIGHLIGHT:-'fg=8'}
typeset -g AISUGGEST_PROMPT_OVERRIDE=${AISUGGEST_PROMPT_OVERRIDE:-''}
typeset -g AISUGGEST_DEBUG=${AISUGGEST_DEBUG:-0}
typeset -g AISUGGEST_LOG=${AISUGGEST_LOG:-/tmp/aisuggest.log}

# ============================================================================
# Internal state
# ============================================================================
typeset -g _AISUGGEST_ACTIVE=0
typeset -g _AISUGGEST_SUGGESTION=""
typeset -g _AISUGGEST_BUFFER_AT_SUGGESTION=""
typeset -g _AISUGGEST_LAST_HIGHLIGHT=""
typeset -g _AISUGGEST_ORIG_TAB=""
typeset -g _AISUGGEST_ORIG_RIGHT=""
typeset -g _AISUGGEST_OS=""

# ============================================================================
# System prompt
# ============================================================================
typeset -g _AISUGGEST_BUILTIN_PROMPT='Translate natural language to a single shell command.

RULES:
- Output EXACTLY ONE command, nothing else.
- No explanations, no alternatives, no markdown, no code fences, no backticks.
- If ambiguous, pick the most reasonable interpretation.
- Prefix standard tools with `command` to bypass aliases (e.g. `command ls -la`).

EFFICIENCY:
- Use `-exec {} +` not `-exec {} \;` (one process, not one per item).
- Add bounds on unbounded searches: head, -maxdepth, 2>/dev/null for noisy errors.
- Prefer human-readable flags where appropriate (-h for sizes).

PLATFORM:
- Check <context> for OS. macOS = BSD utilities; Linux = GNU. Flags differ.
- Prefer POSIX-compatible commands when platform-agnostic alternatives exist.

EXAMPLES:
list files                                    -> command ls -la
find python files modified today              -> command find . -name "*.py" -mtime -1
search for TODO in js files                   -> command grep -r "TODO" --include="*.js" .
kill process on port 3000                     -> command lsof -ti:3000 | xargs kill -9
show disk usage by folder sorted by size      -> command du -h -d 1 | sort -hr | head -20
what is listening on port 8080                -> command lsof -i :8080
what time is it in tokyo                      -> TZ="Asia/Tokyo" command date "+%H:%M:%S %Z"
sort fast by byte order                       -> LC_ALL=C command sort file.txt
last 5 git commits with stats                 -> git log --stat -5
recursively replace foo with bar in .txt      -> command find . -name "*.txt" -exec sed -i "" "s/foo/bar/g" {} +
'

# ============================================================================
# Sanitize model output (security boundary)
# ============================================================================
# Strip ANSI escape sequences and control characters before they touch BUFFER
# or POSTDISPLAY. A model that emits crafted escapes could otherwise overwrite
# what we display.
_aisuggest_sanitize() {
  setopt local_options extended_glob
  local input=$1
  local sanitized=$input
  local esc=$'\x1b'
  while [[ $sanitized == *${esc}\[* ]]; do
    sanitized=${sanitized//${esc}\[[0-9;]#[A-Za-z]/}
  done
  sanitized=${sanitized//${esc}/}
  sanitized=${sanitized//[$'\x00'-$'\x08'$'\x0a'-$'\x1f'$'\x7f']/}
  sanitized=${sanitized##[[:space:]]##}
  sanitized=${sanitized%%[[:space:]]##}
  print -r -- "$sanitized"
}

_aisuggest_log() {
  (( AISUGGEST_DEBUG )) || return 0
  print -r -- "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$AISUGGEST_LOG" 2>/dev/null
}

# ============================================================================
# Provider shim — calls _aiagent_invoke with metadata/spinner/prettify off
# ============================================================================
_aisuggest_query() {
  local user_input=$1
  local agent="${AISUGGEST_AGENT:-$(_aiagent_autodetect)}" || return 1

  # Lazy OS detection (matches upstream's context style)
  if [[ -z $_AISUGGEST_OS ]]; then
    if [[ $OSTYPE == darwin* ]]; then
      _AISUGGEST_OS="macOS $(sw_vers -productVersion 2>/dev/null || print 'unknown')"
    else
      _AISUGGEST_OS="Linux"
    fi
  fi

  local sys_prompt="${AISUGGEST_PROMPT_OVERRIDE:-$_AISUGGEST_BUILTIN_PROMPT}"
  local context="<context>
OS: $_AISUGGEST_OS
Shell: ${SHELL:t}
PWD: $PWD
</context>"

  # _aiagent_invoke takes one prompt arg; concatenate system + context + user.
  local prompt="${sys_prompt}

${context}

User: ${user_input}"

  _aisuggest_log "agent=$agent input=$user_input"

  # Optionally pin model. AICAP_*_MODEL is per-agent (see 04_ai_capture.zsh).
  local saved_claude=$AICAP_CLAUDE_MODEL
  local saved_opencode=$AICAP_OPENCODE_MODEL
  local saved_codex=$AICAP_CODEX_MODEL
  local saved_cursor=$AICAP_CURSOR_MODEL
  if [[ -n $AISUGGEST_MODEL ]]; then
    case $agent in
      claude)       AICAP_CLAUDE_MODEL=$AISUGGEST_MODEL ;;
      opencode)     AICAP_OPENCODE_MODEL=$AISUGGEST_MODEL ;;
      codex)        AICAP_CODEX_MODEL=$AISUGGEST_MODEL ;;
      cursor-agent) AICAP_CURSOR_MODEL=$AISUGGEST_MODEL ;;
    esac
  fi

  local reply
  reply=$(AICAP_SHOW_METADATA=0 AICAP_SPINNER=0 AICAP_PRETTIFY=0 \
          _aiagent_invoke "$agent" "$prompt" 2>/dev/null)
  local rc=$?

  AICAP_CLAUDE_MODEL=$saved_claude
  AICAP_OPENCODE_MODEL=$saved_opencode
  AICAP_CODEX_MODEL=$saved_codex
  AICAP_CURSOR_MODEL=$saved_cursor

  (( rc != 0 )) && { _aisuggest_log "agent failed rc=$rc"; return $rc; }

  # Post-filter: keep first non-blank line, strip leading $/# prompt markers,
  # strip surrounding backticks/fences. Defensive against models that ignore
  # the system-prompt instructions.
  reply=$(print -r -- "$reply" \
          | awk 'NF { print; exit }' \
          | sed -E 's/^[[:space:]]*[#$][[:space:]]*//' \
          | sed -E 's/^`+//; s/`+$//' \
          | sed -E 's/^```[a-z]*//' )

  print -r -- "$reply"
}

# ============================================================================
# Ghost text rendering
# ============================================================================
_aisuggest_show_ghost() {
  local suggestion=$1

  # Clear our previous highlight (if any) — match by exact entry so we don't
  # touch other plugins' (zsh-syntax-highlighting, etc).
  if [[ -n $_AISUGGEST_LAST_HIGHLIGHT ]]; then
    region_highlight=("${(@)region_highlight:#$_AISUGGEST_LAST_HIGHLIGHT}")
    _AISUGGEST_LAST_HIGHLIGHT=""
  fi

  if [[ -n $suggestion && $suggestion != $BUFFER ]]; then
    if [[ $suggestion == ${BUFFER}* ]]; then
      # Suggestion extends current buffer — pure inline completion
      POSTDISPLAY="${suggestion#$BUFFER}"
    else
      # Suggestion replaces — render with Tab-hint indicator
      POSTDISPLAY="  ⇥  ${suggestion}"
    fi
    local start=$#BUFFER
    local end=$(( start + $#POSTDISPLAY ))
    _AISUGGEST_LAST_HIGHLIGHT="$start $end $AISUGGEST_HIGHLIGHT"
    region_highlight+=("$_AISUGGEST_LAST_HIGHLIGHT")
    _aisuggest_log "show_ghost: POSTDISPLAY=[$POSTDISPLAY] start=$start end=$end rh_count=${#region_highlight}"
  else
    POSTDISPLAY=""
    _aisuggest_log "show_ghost: cleared (suggestion empty or matches BUFFER)"
  fi
}

# ============================================================================
# Activate / deactivate state machine
# ============================================================================
# On activate: snapshot Tab and right-arrow bindings, then swap them for our
# accept handlers. On deactivate: restore originals and clear ghost+highlight.
_aisuggest_activate() {
  (( _AISUGGEST_ACTIVE )) && return
  _AISUGGEST_ACTIVE=1
  _AISUGGEST_BUFFER_AT_SUGGESTION="$BUFFER"

  _AISUGGEST_ORIG_TAB=$(bindkey -M main '^I' 2>/dev/null | awk '{print $2}')
  [[ $_AISUGGEST_ORIG_TAB == _aisuggest_accept_tab ]] && _AISUGGEST_ORIG_TAB=""
  _AISUGGEST_ORIG_RIGHT=$(bindkey -M main '^[[C' 2>/dev/null | awk '{print $2}')
  [[ $_AISUGGEST_ORIG_RIGHT == _aisuggest_accept_right ]] && _AISUGGEST_ORIG_RIGHT=""

  bindkey '^I'   _aisuggest_accept_tab
  bindkey '^[[C' _aisuggest_accept_right

  _aisuggest_log "activate: orig_tab=[$_AISUGGEST_ORIG_TAB] orig_right=[$_AISUGGEST_ORIG_RIGHT]"
}

_aisuggest_deactivate() {
  (( ! _AISUGGEST_ACTIVE )) && return
  _aisuggest_log "deactivate: called from ${funcstack[2]:-?} (POSTDISPLAY was [$POSTDISPLAY])"
  _AISUGGEST_ACTIVE=0
  _AISUGGEST_SUGGESTION=""
  _AISUGGEST_BUFFER_AT_SUGGESTION=""
  POSTDISPLAY=""

  if [[ -n $_AISUGGEST_LAST_HIGHLIGHT ]]; then
    region_highlight=("${(@)region_highlight:#$_AISUGGEST_LAST_HIGHLIGHT}")
    _AISUGGEST_LAST_HIGHLIGHT=""
  fi

  if [[ -n $_AISUGGEST_ORIG_TAB ]]; then
    bindkey '^I' "$_AISUGGEST_ORIG_TAB"
  else
    bindkey '^I' expand-or-complete
  fi
  if [[ -n $_AISUGGEST_ORIG_RIGHT ]]; then
    bindkey '^[[C' "$_AISUGGEST_ORIG_RIGHT"
  else
    bindkey '^[[C' forward-char
  fi
}

# ============================================================================
# Hooks
# ============================================================================
# Pre-redraw: if buffer changed, decide whether to keep the suggestion (still
# a prefix match) or dismiss (diverged).
_aisuggest_pre_redraw() {
  (( ! _AISUGGEST_ACTIVE )) && return

  _aisuggest_log "pre_redraw: BUFFER=[$BUFFER] snap=[$_AISUGGEST_BUFFER_AT_SUGGESTION] POSTDISPLAY=[$POSTDISPLAY]"

  if [[ $BUFFER != $_AISUGGEST_BUFFER_AT_SUGGESTION ]]; then
    if [[ -n $BUFFER && $_AISUGGEST_SUGGESTION == ${BUFFER}* ]]; then
      _aisuggest_show_ghost "$_AISUGGEST_SUGGESTION"
      _AISUGGEST_BUFFER_AT_SUGGESTION="$BUFFER"
    else
      _aisuggest_deactivate
    fi
  elif [[ -z $POSTDISPLAY && -n $_AISUGGEST_SUGGESTION ]]; then
    # POSTDISPLAY was cleared by another hook (e.g. zsh-autosuggestions). Re-assert.
    _aisuggest_log "pre_redraw: POSTDISPLAY was cleared externally — re-asserting"
    _aisuggest_show_ghost "$_AISUGGEST_SUGGESTION"
  fi
}

# Line-finish: deactivate before line submission so Tab/→ are restored before
# the next prompt.
_aisuggest_line_finish() {
  (( _AISUGGEST_ACTIVE )) && _aisuggest_deactivate
}

# ============================================================================
# Main widget — Alt+; (or AISUGGEST_KEY) requests a suggestion
# ============================================================================
_aisuggest_widget() {
  _aisuggest_log "widget: enter, BUFFER=[$BUFFER]"
  [[ -z $BUFFER ]] && { _aisuggest_log "widget: empty buffer, return"; return; }

  local spinner='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
  local i=0
  local tmpfile
  tmpfile=$(mktemp -t aisuggest.XXXXXX) || { _aisuggest_log "widget: mktemp failed"; return 1; }
  _aisuggest_log "widget: tmpfile=$tmpfile"

  setopt local_options no_notify no_monitor clobber
  ( _aisuggest_query "$BUFFER" > "$tmpfile" 2>>"${tmpfile}.err" ) &!
  local pid=$!
  _aisuggest_log "widget: backgrounded pid=$pid"

  # Animate spinner on POSTDISPLAY while waiting; any keypress cancels.
  local cancelled=0
  while kill -0 $pid 2>/dev/null; do
    POSTDISPLAY=" ${spinner:$((i % 10)):1}"
    zle -R
    if read -t 0.1 -k 1; then
      _aisuggest_log "widget: read cancelled at i=$i (key='$REPLY')"
      kill $pid 2>/dev/null
      POSTDISPLAY=""
      rm -f "$tmpfile" "${tmpfile}.err"
      cancelled=1
      break
    fi
    ((i++))
  done
  (( cancelled )) && return

  wait $pid 2>/dev/null
  _aisuggest_log "widget: spinner exited at i=$i, reading tmpfile"

  local raw raw_err
  raw=$(<"$tmpfile")
  [[ -f "${tmpfile}.err" ]] && raw_err=$(<"${tmpfile}.err")
  rm -f "$tmpfile" "${tmpfile}.err"
  _aisuggest_log "widget: raw stdout (len=${#raw})=[$raw]"
  [[ -n $raw_err ]] && _aisuggest_log "widget: raw stderr=[$raw_err]"

  local suggestion
  suggestion=$(_aisuggest_sanitize "$raw")
  _aisuggest_log "widget: sanitized (len=${#suggestion})=[$suggestion]"

  if [[ -n $suggestion ]]; then
    _AISUGGEST_SUGGESTION=$suggestion
    _aisuggest_show_ghost "$suggestion"
    _aisuggest_activate
    zle -R
    _aisuggest_log "widget: rendered ghost, activated"
  else
    POSTDISPLAY=""
    zle -M "aisuggest: no suggestion"
    _aisuggest_log "widget: empty suggestion → 'no suggestion' branch"
  fi
}

# ============================================================================
# Accept handlers (only intercept while active; fall through to original)
# ============================================================================
_aisuggest_accept_tab() {
  if [[ -n $_AISUGGEST_SUGGESTION ]] && (( _AISUGGEST_ACTIVE )); then
    BUFFER=$_AISUGGEST_SUGGESTION
    CURSOR=$#BUFFER
    _aisuggest_deactivate
  elif [[ -n $_AISUGGEST_ORIG_TAB ]]; then
    zle "$_AISUGGEST_ORIG_TAB"
  else
    zle expand-or-complete
  fi
}

_aisuggest_accept_right() {
  if [[ -n $_AISUGGEST_SUGGESTION ]] && (( _AISUGGEST_ACTIVE )); then
    BUFFER=$_AISUGGEST_SUGGESTION
    CURSOR=$#BUFFER
    _aisuggest_deactivate
  elif [[ -n $_AISUGGEST_ORIG_RIGHT ]]; then
    zle "$_AISUGGEST_ORIG_RIGHT"
  else
    zle .forward-char
  fi
}

# ============================================================================
# Registration
# ============================================================================
zle -N aisuggest               _aisuggest_widget
zle -N _aisuggest_accept_tab
zle -N _aisuggest_accept_right
zle -N zle-line-finish         _aisuggest_line_finish

# Trigger key (also rebound by zvm_after_init in dot_zshrc.tmpl after
# zsh-vi-mode wipes bindings on init).
bindkey -M emacs "$AISUGGEST_KEY" aisuggest
bindkey -M viins "$AISUGGEST_KEY" aisuggest
bindkey -M vicmd "$AISUGGEST_KEY" aisuggest

# Pre-redraw hook for buffer-change detection. Use add-zle-hook-widget when
# available so we chain alongside zsh-syntax-highlighting / zsh-autosuggestions
# rather than overriding zle-line-pre-redraw.
autoload -Uz add-zle-hook-widget 2>/dev/null
if (( ${+functions[add-zle-hook-widget]} )); then
  add-zle-hook-widget line-pre-redraw _aisuggest_pre_redraw
else
  zle -N zle-line-pre-redraw _aisuggest_pre_redraw
fi

# Tell zsh-autosuggestions to NOT wrap our widgets. Without this, autosuggestions
# wraps every non-underscore-prefixed widget as a "modify" widget (its bind logic
# at zsh-autosuggestions.zsh:220-221), which saves+restores POSTDISPLAY around
# the wrapped invocation — clobbering the ghost text we just set. The
# autosuggestions precmd hook (re)binds widgets every prompt, so this list is
# read fresh; appending here is sufficient.
typeset -ga ZSH_AUTOSUGGEST_IGNORE_WIDGETS
ZSH_AUTOSUGGEST_IGNORE_WIDGETS+=(aisuggest _aisuggest_accept_tab _aisuggest_accept_right _aisuggest_pre_redraw)

# ============================================================================
# CLI invocation — same pipeline as the widget, no ZLE
# ============================================================================
# `aisuggest "natural language"`           -> prints suggested command to stdout
# `aisuggest --debug "natural language"`   -> also prints each layer to stderr:
#                                              agent + envs, raw agent reply,
#                                              after sanitize, after post-filter
# `aisuggest -h | --help`                  -> usage
#
# Use this when the Alt+; widget seems to do nothing (spinner runs, no ghost
# text appears) — `--debug` shows where the pipeline is dropping output.
aisuggest() {
  emulate -L zsh
  local debug=0 want_help=0
  while [[ $# -gt 0 && $1 == -* ]]; do
    case $1 in
      --debug)    debug=1; shift ;;
      -h|--help)  want_help=1; shift ;;
      --)         shift; break ;;
      *)          print -u2 "aisuggest: unknown flag '$1' (try --help)"; return 2 ;;
    esac
  done

  if (( want_help )) || [[ $# -eq 0 ]]; then
    cat >&2 <<'USAGE'
usage: aisuggest [--debug] <natural-language description>

Same pipeline as the Alt+; (or $AISUGGEST_KEY) ZLE widget, but prints the
suggested command to stdout. Use this to debug widget issues without ZLE
in the picture.

  aisuggest "find files larger than 100 MB"
  aisuggest --debug "list 10 largest files in cwd"

Env (see docs/tools/zsh-inline-ai.md):
  AISUGGEST_AGENT=<empty|claude|opencode|codex|cursor-agent>  pin agent
  AISUGGEST_MODEL=<model>                                     pin model
  AISUGGEST_PROMPT_OVERRIDE='...'                             replace prompt
USAGE
    return $(( want_help ? 0 : 2 ))
  fi

  local input="$*"
  local agent="${AISUGGEST_AGENT:-$(_aiagent_autodetect)}" || {
    print -u2 "aisuggest: no agent on PATH (need claude / opencode / codex / cursor-agent)"
    return 1
  }

  if (( ! debug )); then
    _aisuggest_query "$input"
    return $?
  fi

  # --debug: re-run the pipeline manually so we can print each intermediate.
  if [[ -z $_AISUGGEST_OS ]]; then
    if [[ $OSTYPE == darwin* ]]; then
      _AISUGGEST_OS="macOS $(sw_vers -productVersion 2>/dev/null || print 'unknown')"
    else
      _AISUGGEST_OS="Linux"
    fi
  fi
  local sys_prompt="${AISUGGEST_PROMPT_OVERRIDE:-$_AISUGGEST_BUILTIN_PROMPT}"
  local context="<context>
OS: $_AISUGGEST_OS
Shell: ${SHELL:t}
PWD: $PWD
</context>"
  local full_prompt="${sys_prompt}

${context}

User: ${input}"

  {
    print -- "----- aisuggest --debug -----"
    print -- "agent:                $agent"
    print -- "AISUGGEST_KEY:        $AISUGGEST_KEY"
    print -- "AISUGGEST_AGENT:      ${AISUGGEST_AGENT:-<unset; autodetected>}"
    print -- "AISUGGEST_MODEL:      ${AISUGGEST_MODEL:-<unset; using AICAP_*_MODEL>}"
    print -- "AICAP_CLAUDE_MODEL:   $AICAP_CLAUDE_MODEL"
    print -- "AICAP_OPENCODE_MODEL: $AICAP_OPENCODE_MODEL"
    print -- "AICAP_CODEX_MODEL:    $AICAP_CODEX_MODEL"
    print -- "AICAP_CURSOR_MODEL:   ${AICAP_CURSOR_MODEL:-<unset>}"
    print -- "input:                $input"
    print -- "system prompt size:   $#sys_prompt chars"
    print -- "context:              $context"
    print -- "----- invoking _aiagent_invoke (rc + raw stdout below; stderr next) -----"
  } >&2

  local raw stderr_log
  stderr_log=$(mktemp -t aisuggest.err.XXXXXX) || return 1
  raw=$(AICAP_SHOW_METADATA=0 AICAP_SPINNER=0 AICAP_PRETTIFY=0 \
        _aiagent_invoke "$agent" "$full_prompt" 2>"$stderr_log")
  local rc=$?
  {
    print -- "rc=$rc, raw stdout length=${#raw}"
    print -- "----- raw stdout -----"
    print -r -- "$raw"
    print -- "----- raw stderr -----"
    cat "$stderr_log"
    rm -f "$stderr_log"
  } >&2

  local sanitized
  sanitized=$(_aisuggest_sanitize "$raw")
  print -u2 -- "----- after _aisuggest_sanitize (length=${#sanitized}) -----"
  print -ru2 -- "$sanitized"

  local final
  final=$(print -r -- "$raw" \
          | awk 'NF { print; exit }' \
          | sed -E 's/^[[:space:]]*[#$][[:space:]]*//' \
          | sed -E 's/^`+//; s/`+$//' \
          | sed -E 's/^```[a-z]*//')
  print -u2 -- "----- after post-filter (length=${#final}) — this is what the widget would render -----"
  print -r -- "$final"
  return $rc
}
