# 37_worktrunk.zsh - Worktrunk (`wt`) zsh-only completion generation.
# Shell-init wrapper + wtcd function live in dot_config/shell/37_worktrunk.sh
# (shared bash + zsh). This file only handles ~/.zfunc/_wt completion regen,
# which is zsh-specific.
# https://worktrunk.dev — github.com/max-sixty/worktrunk

# Skip silently if not installed
command -v wt &>/dev/null || return 0

# ── Completion ─────────────────────────────────────────────────────────────
#
# macOS (Homebrew): `_wt` ships in /opt/homebrew/share/zsh/site-functions/
# and is picked up automatically by compinit — nothing to do here.
#
# Linux (ansible drops the bare binary into ~/.local/bin/) has no system
# completion path, so dump clap's auto-generated zsh completer into
# ~/.zfunc/_wt (already on $fpath via dot_zshrc.tmpl). Same pattern as sesh /
# television. Regenerate when wt's version changes.
#
# Worktrunk doesn't expose a `wt completion zsh` subcommand — clap's dynamic
# completer is invoked via `COMPLETE=zsh wt` (with no args). Output is a
# self-contained `#compdef wt` script that handles further completion
# requests by re-invoking the binary with COMPLETE+_CLAP_COMPLETE_INDEX set.
if [[ -d ~/.zfunc ]] && [[ ! -f /opt/homebrew/share/zsh/site-functions/_wt ]] \
                    && [[ ! -f /usr/local/share/zsh/site-functions/_wt ]]; then
    local _wt_ver="$(wt --version 2>/dev/null)"
    if [[ ! -f ~/.zfunc/_wt ]] || ! grep -q "${_wt_ver}" ~/.zfunc/_wt 2>/dev/null; then
        {
            print -r -- "# Auto-generated by 37_worktrunk.zsh for ${_wt_ver}"
            COMPLETE=zsh wt 2>/dev/null
        } > ~/.zfunc/_wt
    fi
fi
