# 37_worktrunk.zsh - Worktrunk (`wt`) git worktree manager
# https://worktrunk.dev — github.com/max-sixty/worktrunk
#
# Companion config: ~/.config/worktrunk/config.toml (managed by chezmoi at
# dot_config/worktrunk/config.toml). Aliases like `wt sw` / `wt cc` live
# THERE, not here — keep this file focused on shell-level integration only.

# Skip silently if not installed (Linux ansible install can fail offline)
command -v wt &>/dev/null || return 0

# ── Shell integration: cd-wrapping `wt` function ───────────────────────────
#
# `wt switch` needs to change the parent shell's $PWD, which a normal binary
# can't do. Worktrunk solves this by writing a directive file that a wrapper
# shell function reads and `cd`s to. We eval that wrapper at shell startup
# rather than running `wt config shell install` (which edits ~/.zshrc with a
# block chezmoi would fight over).
#
# Same pattern as starship / zoxide / direnv elsewhere in this directory.
eval "$(wt config shell init zsh 2>/dev/null)"

# ── Completion ─────────────────────────────────────────────────────────────
#
# macOS (Homebrew): `_wt` ships in /opt/homebrew/share/zsh/site-functions/
# and is picked up automatically by compinit — nothing to do here.
#
# Linux (ansible drops the bare binary into ~/.local/bin/) has no system
# completion path, so dump clap's auto-generated zsh completer into
# ~/.zfunc/_wt (already on $fpath via dot_zshrc.tmpl). Same pattern as sesh /
# television. Regenerate when wt's version changes.
#
# Worktrunk doesn't expose a `wt completion zsh` subcommand — clap's dynamic
# completer is invoked via `COMPLETE=zsh wt` (with no args). Output is a
# self-contained `#compdef wt` script that handles further completion
# requests by re-invoking the binary with COMPLETE+_CLAP_COMPLETE_INDEX set.
if [[ -d ~/.zfunc ]] && [[ ! -f /opt/homebrew/share/zsh/site-functions/_wt ]] \
                    && [[ ! -f /usr/local/share/zsh/site-functions/_wt ]]; then
    local _wt_ver="$(wt --version 2>/dev/null)"
    if [[ ! -f ~/.zfunc/_wt ]] || ! grep -q "${_wt_ver}" ~/.zfunc/_wt 2>/dev/null; then
        {
            print -r -- "# Auto-generated by 37_worktrunk.zsh for ${_wt_ver}"
            COMPLETE=zsh wt 2>/dev/null
        } > ~/.zfunc/_wt
    fi
fi

# ── Tiny zsh-side conveniences (NOT duplicating wt's own aliases) ─────────
#
# `wt`'s own aliases (sw / ls / rm / cc / oc) are defined in
# ~/.config/worktrunk/config.toml so they work from any shell + the
# interactive picker. Anything below is ZSH-ONLY niceness that wt's alias
# system can't express.

# `wtcd` — jump to a worktree path WITHOUT switching tmux/sesh session.
# Useful when you want to peek at sibling worktree files (open in nvim split,
# scp, etc.) without disturbing the current pane's session context.
function wtcd() {
    local target
    target=$(wt list --format=json 2>/dev/null \
        | jq -r '.worktrees[].path' \
        | fzf-tmux -p 60%,40% --prompt='wt cd ❯ ' --header='Pick a worktree to cd into') \
        || return
    [[ -n "$target" ]] && cd -- "$target"
}
